const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');let job=null,frame=null,png=null,cut=0,busy=false,playing=false,timer=null,drag=null,fileVersion=0;
const defaults=i=>({x:.5,y:.5,size:1,angle:i===0?-5:0,zoom:i===0?1.10:1.20,bx:.5,by:.5});let layouts=[defaults(0),defaults(1)];const se=new Audio('./audio/baretemasu_se.wav');
const loadImage=src=>new Promise((ok,no)=>{const im=new Image();im.onload=()=>ok(im);im.onerror=()=>no(Error('画像を読み込めません。'));im.src=src;});
const resources=Promise.all([loadImage('./assets/bare.png'),document.fonts.load('40px Tsunagi')]).then(([p])=>png=p);
const font=new FontFace('Tsunagi','url(./fonts/TsunagiGothic.ttf)');document.fonts.add(font);const fontReady=font.load();
function lines(){return $('caption').value.split('\n').slice(0,4).map(x=>x.trim()).filter(Boolean);}
function emphasisOptions(){const old=$('emphasis').value;$('emphasis').replaceChildren();lines().forEach((line,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+'行目：'+line;$('emphasis').append(o);});$('emphasis').value=Math.min(Number(old)||0,Math.max(0,lines().length-1));}
function paint(index=cut,target=ctx){if(!frame||!png||!job)return;const w=job.width,h=job.height,l=layouts[index];target.clearRect(0,0,w,h);target.fillStyle='#061315';target.fillRect(0,0,w,h);target.drawImage(frame,l.bx*w-w*l.zoom/2,l.by*h-h*l.zoom/2,w*l.zoom,h*l.zoom);target.save();target.translate(l.x*w,l.y*h);target.rotate(l.angle*Math.PI/180);if(index===1){const ratio=Math.min(w/png.width,h/png.height)*l.size;target.drawImage(png,-png.width*ratio/2,-png.height*ratio/2,png.width*ratio,png.height*ratio);}else{const rows=lines(),selected=Number($('emphasis').value);let base=Math.min(w*.22,h*.19);rows.forEach((line,i)=>{const factor=i===selected?1:.68;target.font=`${base*factor}px Tsunagi`;base=Math.min(base,(w*.91/target.measureText(line).width)*base);});base*=l.size;const sizes=rows.map((_,i)=>base*(i===selected?1:.68)),gap=base*.22,total=sizes.reduce((a,b)=>a+b,0)+gap*Math.max(0,rows.length-1);let y=-total/2;target.fillStyle='#fff';target.textAlign='center';target.textBaseline='top';rows.forEach((line,i)=>{target.font=`${sizes[i]}px Tsunagi`;target.fillText(line,0,y);y+=sizes[i]+gap;});}target.restore();}
function controls(){const l=layouts[cut];$('freeFields').hidden=cut===1;$('size').value=l.size*100;$('angle').value=l.angle;$('zoom').value=l.zoom*100;$('sizeValue').textContent=Math.round(l.size*100)+'%';$('angleValue').textContent=l.angle+'°';$('zoomValue').textContent=Math.round(l.zoom*100)+'%';[0,1].forEach(i=>$('tab'+i).classList.toggle('active',cut===i));}
function invalidate(){ $('download').hidden=true;$('result').hidden=true; }
function enable(){const ready=job&&frame&&!busy&&!playing;$('settings').disabled=!ready;for(const id of ['tab0','tab1','play','render'])$(id).disabled=!ready; $('render').disabled=!ready||!lines().length;$('file').disabled=busy||playing;$('cancel').hidden=!busy;}
function stop(){playing=false;clearTimeout(timer);se.pause();se.currentTime=5;controls();paint();enable();}
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(f.size>100*1024*1024){$('status').textContent='100MB以下のMP4を選んでください。';return;}const version=++fileVersion;busy=true;job=null;frame=null;canvas.hidden=true;$('empty').hidden=false;invalidate();enable();$('status').textContent='動画を読み込み、最終フレームを準備しています…';try{await Promise.all([resources,fontReady]);const j=await engine.prepare(f);if(version!==fileVersion)return;job={...j};frame=await loadImage(j.frame);canvas.width=j.width;canvas.height=j.height;layouts=[defaults(0),defaults(1)];cut=0;canvas.hidden=false;$('empty').hidden=true;controls();paint();$('status').textContent=`${j.duration.toFixed(1)}秒 → ${(j.duration+3).toFixed(1)}秒。配置を調整してください。`;}catch(e){console.error('ENGINE ERROR',String(e),e?.stack);$('status').textContent=e.message||String(e);}finally{busy=false;enable();}};
[0,1].forEach(i=>$('tab'+i).onclick=()=>{cut=i;controls();paint();});$('caption').oninput=()=>{emphasisOptions();invalidate();paint();enable();};$('emphasis').onchange=()=>{invalidate();paint();};for(const [id,key,factor] of [['size','size',.01],['angle','angle',1],['zoom','zoom',.01]])$(id).oninput=()=>{layouts[cut][key]=Number($(id).value)*factor;controls();invalidate();paint();};$('reset').onclick=()=>{layouts[cut]=defaults(cut);controls();invalidate();paint();};
canvas.onpointerdown=e=>{if(busy||playing||!job)return;canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,layout:{...layouts[cut]},target:$('target').value};};canvas.onpointermove=e=>{if(!drag)return;const rect=canvas.getBoundingClientRect(),l=layouts[cut],dx=(e.clientX-drag.x)/rect.width,dy=(e.clientY-drag.y)/rect.height;const keys=drag.target==='title'?['x','y']:['bx','by'];l[keys[0]]=Math.max(-.2,Math.min(1.2,drag.layout[keys[0]]+dx));l[keys[1]]=Math.max(-.2,Math.min(1.2,drag.layout[keys[1]]+dy));invalidate();paint();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
$('play').onclick=async()=>{playing=true;enable();cut=0;controls();paint();se.currentTime=5;try{await se.play();}catch(e){$('status').textContent='SEを再生できませんでした。';}timer=setTimeout(()=>{cut=1;controls();paint();timer=setTimeout(stop,1500);},1500);};
$('render').onclick=async()=>{busy=true;enable();invalidate();$('status').textContent='配置を反映して動画を生成しています…';try{const off=document.createElement('canvas');off.width=job.width;off.height=job.height;const c=off.getContext('2d'),scenes=[];for(let i=0;i<2;i++){paint(i,c);scenes.push(off.toDataURL('image/png'));}const result=await engine.render(job,scenes);$('result').src=result.url;$('result').hidden=false;$('download').href=result.url;$('download').hidden=false;$('status').textContent='完成しました · '+result.total.toFixed(1)+'秒。';}catch(e){console.error('ENGINE ERROR',String(e),e?.stack);$('status').textContent=e.message||String(e);}finally{busy=false;enable();}};emphasisOptions();controls();

$('cancel').onclick=()=>{engine.cancel();job=null;frame=null;invalidate();$('status').textContent='処理を中止しました。動画を選び直してください。';};
